export const drawings = [
	{
		"id": 1,
		"jump": "pilgimage",
		"title": "The Pilgrimage",
		"pic": "../img/drawings/pilgrimage.jpg",
		"size": "12x16 in.",
		"medium": "Copic Marker, Micron Pen",
		"year": "2020",
		"desc": "Part of the ink spiral series.",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 2,
		"jump": "drone",
		"title": "Drone Seeker",
		"pic": "../img/drawings/drone-seeker.jpg",
		"size": "12x16 in.",
		"medium": "Copic Market, Micron Pen",
		"year": "2020",
		"desc": "Part of the ink spiral series.",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 3,
		"jump": "nectar",
		"title": "The Last Nectar",
		"pic": "../img/drawings/the-last-nectar.jpg",
		"size": "16x12 in.",
		"medium": "Graphite, Charcoal",
		"year": "2018",
		"desc": "Harvesting at night.",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 4,
		"jump": "escape",
		"title": "The Escape",
		"pic": "../img/drawings/the-escape.jpg",
		"size": "16x12 in.",
		"medium": "Graphite, Charcoal",
		"year": "2018",
		"desc": "Running from the waves.",
		"left": "imagewide",
		"right": "slim"
	},
	{
		"id": 5,
		"jump": "transmission",
		"title": "Transmission / Reflection",
		"pic": "../img/drawings/transmission.jpg",
		"size": "16x12 in.",
		"medium": "Graphite, Charcoal",
		"year": "2018",
		"desc": "Sending those signals.",
		"left": "imagewide",
		"right": "slim"
	},
	{
		"id": 6,
		"jump": "flooded",
		"title": "Flooded",
		"pic": "../img/drawings/flooded.jpg",
		"size": "12x16 in.",
		"medium": "Graphite, Charcoal",
		"year": "2018",
		"desc": "We'll go back the other way.",
		"left": "image",
		"right": "reg"
	},
]