export const dreamcards = [
	{
		"id": 1,
		"title": "XX • The Awakening",
		"jump": "cards20",
		"pic": "../img/dreamcards/20-theawakening.jpg",
	},
	{
		"id": 2,
		"title": "XIX • The Multiverse",
		"jump": "",
		"pic": "../img/dreamcards/19-themultiverse.jpg",
	},
	{
		"id": 3,
		"title": "XVIII • The Phoenix",
		"jump": "",
		"pic": "../img/dreamcards/18-thephoenix.jpg",
	},
	{
		"id": 4,
		"title": "XVII • The Oasis",
		"jump": "",
		"pic": "../img/dreamcards/17-theoasis.jpg",
	},
	{
		"id": 5,
		"title": "XVI • The Waterfall",
		"jump": "",
		"pic": "../img/dreamcards/16-thewaterfall.jpg",
	},
	{
		"id": 6,
		"title": "XV • The Owl",
		"jump": "cards15",
		"pic": "../img/dreamcards/15-theowl.jpg",
	},
	{
		"id": 7,
		"title": "XIV • The Constellation",
		"jump": "",
		"pic": "../img/dreamcards/14-theconstellation.jpg",
	},
	{
		"id": 8,
		"title": "XIII • The Whale",
		"jump": "",
		"pic": "../img/dreamcards/13-thewhale.jpg",
	},
	{
		"id": 9,
		"title": "XII • The Willow",
		"jump": "",
		"pic": "../img/dreamcards/12-thewillow.jpg",
	},
	{
		"id": 10,
		"title": "XI • The Hourglass",
		"jump": "",
		"pic": "../img/dreamcards/11-thehourglass.jpg",
	},
	{
		"id": 11,
		"title": "X • The Ink & Quill",
		"jump": "cards10",
		"pic": "../img/dreamcards/10-theinkandquill.jpg",
	},
	{
		"id": 12,
		"title": "IX • The Castle",
		"jump": "",
		"pic": "../img/dreamcards/09-thecastle.jpg",
	},
	{
		"id": 13,
		"title": "VIII • The Bridge",
		"jump": "",
		"pic": "../img/dreamcards/08-thebridge.jpg",
	},
	{
		"id": 14,
		"title": "VII • The Lantern",
		"jump": "",
		"pic": "../img/dreamcards/07-thelantern.jpg",
	},
	{
		"id": 15,
		"title": "VI • The Lighthouse",
		"jump": "",
		"pic": "../img/dreamcards/06-thelighthouse.jpg",
	},
	{
		"id": 16,
		"title": "V • The Cavern",
		"jump": "cards5",
		"pic": "../img/dreamcards/05-thecavern.jpg",
	},
	{
		"id": 17,
		"title": "IV • The Tempest",
		"jump": "",
		"pic": "../img/dreamcards/04-thetempest.jpg",
	},
	{
		"id": 18,
		"title": "III • The Deep",
		"jump": "",
		"pic": "../img/dreamcards/03-thedeep.jpg",
	},
	{
		"id": 19,
		"title": "II • The Apparition",
		"jump": "",
		"pic": "../img/dreamcards/02-theapparition.jpg",
	},
	{
		"id": 20,
		"title": "I • The Void",
		"jump": "",
		"pic": "../img/dreamcards/01-thevoid.jpg",
	},
]