export const list = [
	{
		"id": 1,
		"title": "Dream Cards",
		"thumb": "../img/thumb/dreamcards.jpg",
		"desc": "Deck of 20 Illustrative Cards",
		"url": "../works/dreamcards",
	},
	{
		"id": 2,
		"title": "Digital Art",
		"thumb": "../img/thumb/digital.jpg",
		"desc": "Archive of Digital Works",
		"url": "../works/digital",
	},
	{
		"id": 3,
		"title": "Forest Magic",
		"thumb": "../img/thumb/forest.jpg",
		"desc": "Photo Manipulation Series",
		"url": "../works/forest",
	},
	{
		"id": 4,
		"title": "Mountain Waves",
		"thumb": "../img/thumb/waves.jpg",
		"desc": "Photo Manipulation Series",
		"url": "../works/mountain",
	},
	{
		"id": 5,
		"title": "Psychedeliscapes",
		"thumb": "../img/thumb/psych.jpg",
		"desc": "Photo Manipulation Series",
		"url": "../works/psych",
	},
	{
		"id": 6,
		"title": "Digital Art Prints",
		"thumb": "../img/thumb/prints.jpg",
		"desc": "Works on 16x20in Fine Art Paper",
		"url": "../works/prints",
	},
	{
		"id": 7,
		"title": "Drawings",
		"thumb": "../img/thumb/drawings.jpg",
		"desc": "Charcoal, Graphite, Ink",
		"url": "../works/drawings",
	},
	{
		"id": 8,
		"title": "Paintings",
		"thumb": "../img/thumb/paintings.jpg",
		"desc": "Oil, Acrylic, Watercolor",
		"url": "../works/paintings",
	},
	{
		"id": 9,
		"title": "Digital Photo",
		"thumb": "../img/thumb/photo.jpg",
		"desc": "Archive of Digital Photography",
		"url": "../works/photo",
	},
	{
		"id": 10,
		"title": "Client Work",
		"thumb": "../img/thumb/client.jpg",
		"desc": "Artwork Commissioned by Others",
		"url": "../works/client",
	},
]