export const paintings = [
	{
		"id": 1,
		"jump": "fragment",
		"title": "Fragment",
		"pic": "../img/paintings/fragment.jpg",
		"size": "24x30 in.",
		"medium": "Oil & Acrylic on Canvas",
		"year": "2017",
		"desc": "",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 2,
		"jump": "connected",
		"title": "Connected",
		"pic": "../img/paintings/connected.jpg",
		"size": "24x30 in.",
		"medium": "Oil & Acrylic on Canvas",
		"year": "2017",
		"desc": "",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 3,
		"jump": "magic fades",
		"title": "The Magic Fades",
		"pic": "../img/paintings/the-magic-fades.jpg",
		"size": "48x36 in.",
		"medium": "Oil & Acrylic on Canvas",
		"year": "2018",
		"desc": "",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 4,
		"jump": "giants",
		"title": "Among Giants II",
		"pic": "../img/paintings/among-giants-ii.jpg",
		"size": "24x36 in.",
		"medium": "Oil & Acrylic on Canvas",
		"year": "2016",
		"desc": "The second in a series",
		"left": "image",
		"right": "reg"
	},
	{
		"id": 5,
		"jump": "zodiak",
		"title": "Zodiak",
		"pic": "../img/paintings/zodiak.jpg",
		"size": "12x16 in.",
		"medium": "Watercolor, Gouache, India Ink on Cold-Press Arches Watercolor Paper",
		"year": "2021",
		"desc": "",
		"left": "image",
		"right": "reg"
	},
	{
		"id": 6,
		"jump": "puddle",
		"title": "Puddle",
		"pic": "../img/paintings/puddle.jpg",
		"size": "16x12 in.",
		"medium": "India Ink & Gouache on Cold-Press Arches Watercolor Paper",
		"year": "2020",
		"desc": "",
		"left": "imagewide",
		"right": "slim"
	},
	{
		"id": 7,
		"jump": "stoughton",
		"title": "Evening at Stoughton Pond",
		"pic": "../img/paintings/stoughton-pond.jpg",
		"size": "40x16 in.",
		"medium": "Oil & Acrylic on Canvas",
		"year": "2016",
		"desc": "",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 8,
		"jump": "time",
		"title": "Time As a Circle",
		"pic": "../img/paintings/time-as-a-circle.jpg",
		"size": "36x36 in.",
		"medium": "Oil & Acrylic on Canvas",
		"year": "2014",
		"desc": "",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 9,
		"jump": "robinmoth",
		"title": "Robin Moth",
		"pic": "../img/paintings/robin-moth.jpg",
		"size": "28x22 in.",
		"medium": "Oil & Acrylic on Canvas",
		"year": "2016",
		"desc": "",
		"left": "imagewide",
		"right": "slim",
	},
]	