export const photos = [
	{
		"id": 1,
		"jump": "campfiresky",
		"title": "Campfire Sky",
		"pic": "../img/photo/campfire-sky.jpg",
		"year": "2019",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 2,
		"jump": "night",
		"title": "Night Blanket",
		"pic": "../img/photo/nightblanket.jpg",
		"year": "2019",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 3,
		"jump": "therefuge",
		"title": "The Refuge",
		"pic": "../img/photo/the-refuge.jpg",
		"year": "2017",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 4,
		"jump": "ceremony",
		"title": "Ceremony",
		"pic": "../img/photo/ceremony.jpg",
		"year": "2017",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 5,
		"jump": "mistyday1",
		"title": "Misty Day I",
		"pic": "../img/photo/mistyday-i.jpg",
		"year": "2017",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 6,
		"jump": "mistyday2",
		"title": "Misty Day II",
		"pic": "../img/photo/mistyday-ii.jpg",
		"year": "2017",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 7,
		"jump": "bird",
		"title": "Bird Sanctuary",
		"pic": "../img/photo/bird-sanctuary.jpg",
		"year": "2018",
		"left": "imagewide",
		"right": "slim",
	},
	{
		"id": 8,
		"jump": "kettle",
		"title": "Kettle Pond, VT",
		"pic": "../img/photo/kettle-pond.jpg",
		"year": "2018",
		"left": "imagewide",
		"right": "slim",
	},
]