export const prints = [
	{
		"id": 1,
		"jump": "cycles",
		"title": "Cycles",
		"pic": "../img/prints/cycles.jpg",
		"year": "2018",
		"size": "16in. x 20in.",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 2,
		"jump": "newelement",
		"title": "New Element",
		"pic": "../img/prints/new-element.jpg",
		"year": "2019",
		"size": "16in. x 20in.",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 3,
		"jump": "eye",
		"title": "Eye Sea",
		"pic": "../img/prints/eye-sea.jpg",
		"year": "2017",
		"size": "16in. x 20in.",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 4,
		"jump": "modernvertigo",
		"title": "Modern Vertigo",
		"pic": "../img/prints/modern-vertigo.jpg",
		"year": "2018",
		"size": "16in. x 20in.",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 5,
		"jump": "sink",
		"title": "Sink Into The Sky",
		"pic": "../img/prints/sink-into-the-sky.jpg",
		"year": "2018",
		"size": "16in. x 20in.",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 6,
		"jump": "shapeshifter",
		"title": "Shapeshifter",
		"pic": "../img/prints/shapeshifter.jpg",
		"year": "2018",
		"size": "16in. x 20in.",
		"left": "image",
		"right": "reg",
	},
	{
		"id": 7,
		"jump": "theotherisland",
		"title": "The Other Island",
		"pic": "../img/prints/the-other-island.jpg",
		"year": "2017",
		"size": "16in. x 20in.",
		"left": "image",
		"right": "reg",
	},
]